name: 'Rebase'
description: 'Rebase '

inputs:
  github_token:
    description: The GITHUB_TOKEN secret
    required: true

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'arrow-up-right'
  color: 'green'
